{% set name = "FLAML" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 4a1ec289ddaec36850cfc66f6fb335b8521df49ea31f6adb54ea63a5cebb6865

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.17.0rc1
    - lightgbm >=2.3.1
    - xgboost >=0.90
    - scipy >=1.4.1
    - pandas >=1.1.4
    - scikit-learn >=0.24
    - python >=3.6

test:
  requires:
    - pip
    - pytest
    - pandas >=1.1.4
    - scikit-learn >=0.24
  source_files:
    # list all conda related test files here
    # note: keep the conda related tests directly in the test folder, so that bundling to tar.gz includes them
    # or just extend the test_conda_distribution.py file with more tests (and make sure to mark it as conda)
    - test/test_conda_distribution.py
  commands:
    - pytest -m conda

about:
  home: https://github.com/microsoft/FLAML
  summary: A fast and lightweight autoML system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michalchromcak
    - skzhang1
