{% set name = "FLAML" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33102862a21c63d004f78e1349ccd55753e3534bfcdcb6e65a08562c14d69e44

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.17.0rc1
    - lightgbm >=2.3.1
    - xgboost >=0.90
    - scipy >=1.4.1
    - pandas >=1.1.4
    - scikit-learn >=0.24
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest
    - pandas >=1.1.4
    - scikit-learn >=0.24
    - python {{ python_min }}
  source_files:
    # list all conda related test files here
    # note: keep the conda related tests directly in the test folder, so that bundling to tar.gz includes them
    # or just extend the test_conda_distribution.py file with more tests (and make sure to mark it as conda)
    - test/test_conda_distribution.py
  commands:
    - pytest -m conda

about:
  home: https://github.com/microsoft/FLAML
  summary: A fast and lightweight autoML system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michalchromcak
    - skzhang1
